GridLayout:
	cols: 2
	
	Button:
		id: service_tag_but
		text: "service tag"
	TextInput:
		id: service_tag_text
		text: "type something here"
	Button:
		id: system_type_but
		text: 
	Label:
		id: system_type_text
		text: "system type"
	Button: 
		id: RAID_but
		text: 
	Label:
		id: RAID_text
		text: "RAID"
	Button:
		id: iDRAC_but
		text:
	Label:
		id: iDRAC_text
		text: "iDRAC"
	Button: 
		id: HD_but
		text:
	Label:
		id: HD_text
		text: "hard drive"